config/routes.rb
Rails.application.routes.draw do

  resources :event_spaces
  resources :spaces
  get 'profiles/service'
  get 'profiles/user'
  get 'profiles/rental'
  get 'profiles/update_item'
  get 'profiles/dashboard'
  get 'profiles/listing'
  get 'profiles/update_listing'
  
  get 'items/categories'
  
  root 'home#index'
  # get '*path',  to: 'home#index'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords', :omniauth_callbacks => 'omniauth_callbacks'}

  resources :reviews
  resources :home
  resources :stores
  resources :items
  resources :profiles
  resources :help
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/amenity.rb
class Amenity < ApplicationRecord
  has_many :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_one :space
end

app/models/event_space.rb
class EventSpace < ApplicationRecord
  belongs_to :amenity
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :user
  has_one :category 
end

app/models/user.rb
class User < ApplicationRecord
  # validates :name, :login, :email, presence: true
  validates_presence_of [:email, :password], on: :update
  validates_presence_of [:email, :password, :lastname, :firstname, :birthday], on: :create
  
  #  mount_uploader :avatar, AvatarUploader
  
  acts_as_token_authenticatable
  rolify
  has_many :space
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook] , 
         :authentication_keys => {email: true} 


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.image = auth.info.image
      end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def destroy
  end

  def update
  end
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end
 
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end

  def destroy
  end

  def update
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_space
      @space = Space.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def space_params
      params.require(:space).permit(:name, :description, :location, :guest_capacity, :fee, :user_id, :category_id, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/event_spaces_helper.rb
module EventSpacesHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/spaces/_form.html.erb
<%= form_with(model: space, local: true) do |form| %>
  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :space_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :space_description %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :space_location %>
  </div>

  <div class="field">
    <%= form.label :guest_capacity %>
    <%= form.number_field :guest_capacity, id: :space_guest_capacity %>
  </div>

  <div class="field">
    <%= form.label :fee %>
    <%= form.text_field :fee, id: :space_fee %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :space_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spaces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th>Guest capacity</th>
      <th>Fee</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.name %></td>
        <td><%= space.description %></td>
        <td><%= space.location %></td>
        <td><%= space.guest_capacity %></td>
        <td><%= space.fee %></td>
        <td><%= space.user %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @space.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @space.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @space.location %>
</p>

<p>
  <strong>Guest capacity:</strong>
  <%= @space.guest_capacity %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @space.fee %>
</p>

<p>
  <strong>User:</strong>
  <%= @space.user %>
</p>

<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>